"""Agent config injection — write skill references into CLAUDE.md, .cursorrules, etc."""

from __future__ import annotations

import json
import re
from pathlib import Path

MARKER_START = "<!-- skillm:start -->"
MARKER_END = "<!-- skillm:end -->"

SKILLS_JSON = "skills.json"
SKILLS_DIR = ".skills"


def detect_format(project_dir: Path) -> str:
    """Auto-detect agent config format from project files."""
    if (project_dir / "CLAUDE.md").exists():
        return "claude"
    if (project_dir / ".cursorrules").exists():
        return "cursor"
    if (project_dir / "AGENTS.md").exists():
        return "openclaw"
    return "claude"  # default


def get_config_path(project_dir: Path, fmt: str) -> Path:
    """Get the config file path for the given format."""
    paths = {
        "claude": project_dir / "CLAUDE.md",
        "cursor": project_dir / ".cursorrules",
        "openclaw": project_dir / "AGENTS.md",
        "codex": project_dir / "AGENTS.md",
    }
    return paths.get(fmt, project_dir / "CLAUDE.md")


def generate_section(project_dir: Path) -> str:
    """Generate the skills section content."""
    skills_json = project_dir / SKILLS_JSON
    if not skills_json.exists():
        return ""

    manifest = json.loads(skills_json.read_text())
    skills = manifest.get("skills", {})

    if not skills:
        return ""

    lines = [
        MARKER_START,
        "",
        "## Project Skills (auto-generated by skillm)",
        "",
        "Available skills for this project:",
        "",
    ]

    for name, info in sorted(skills.items()):
        if info.get("enabled", True) is False:
            continue

        version = info.get("version", "latest")
        skill_md = project_dir / SKILLS_DIR / name / "SKILL.md"

        # Try to read description from installed SKILL.md
        description = ""
        if skill_md.exists():
            content = skill_md.read_text(encoding="utf-8")
            # First paragraph after heading
            for line in content.split("\n"):
                line = line.strip()
                if line and not line.startswith("#") and not line.startswith("<!--"):
                    description = line
                    break

        desc_part = f": {description}" if description else ""
        lines.append(f"- **{name}** (v: {version}){desc_part}")
        lines.append(f"  → Read `.skills/{name}/SKILL.md` when relevant")
        lines.append("")

    lines.append("Only read a skill's SKILL.md when the current task matches it.")
    lines.append(MARKER_END)

    return "\n".join(lines)


def inject(project_dir: Path, fmt: str | None = None, config_file: Path | None = None) -> Path:
    """Inject skill references into agent config file. Returns the config file path."""
    if fmt is None or fmt == "auto":
        fmt = detect_format(project_dir)

    target = config_file or get_config_path(project_dir, fmt)
    section = generate_section(project_dir)

    if not section:
        return target

    if target.exists():
        content = target.read_text(encoding="utf-8")
        # Replace existing section
        pattern = re.compile(
            re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
            re.DOTALL,
        )
        if pattern.search(content):
            content = pattern.sub(section, content)
        else:
            content = content.rstrip() + "\n\n" + section + "\n"
    else:
        content = section + "\n"

    target.write_text(content, encoding="utf-8")
    return target
